sudo: required

services:
  - docker

language:
  - python

before_install:
  - docker build -t src386/docker-planetaryimager 0.7.0/

script:
  - docker run --rm -ti src386/docker-planetaryimager file /usr/bin/planetary_imager